# Generated by Django 5.1.6 on 2025-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomprice',
            options={'ordering': ['weekday'], 'verbose_name': 'цена за день недели', 'verbose_name_plural': 'Цены по дням недели'},
        ),
        migrations.AlterUniqueTogether(
            name='roomprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roomprice',
            name='percentage',
            field=models.IntegerField(default=100, help_text='От 0 (бесплатно) до 200 (удвоенная базовая цена)', verbose_name='Процент от базовой цены (%)'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='weekday',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, unique=True, verbose_name='День недели'),
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='room',
        ),
    ]
