# Generated by Django 5.2.8 on 2025-11-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('has_child_bed', models.BooleanField(default=False, help_text='Установить детскую кровать в номере при бронировании', verbose_name='Нужна детская кровать')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость (руб.)')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Бронирование отменено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at',),
            },
        ),
    ]
