# Generated by Django 5.2.8 on 2025-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
